// This file was generated by a tool; you should avoid making direct changes.
// Consider using 'partial classes' to extend these types
// Input: storage.proto

#pragma warning disable CS1591, CS0612, CS3021, IDE1006
[global::ProtoBuf.ProtoContract()]
public partial class Storage : global::ProtoBuf.IExtensible
{
    private global::ProtoBuf.IExtension __pbn__extensionData;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
        => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

    [global::ProtoBuf.ProtoMember(1, Name = @"version", IsRequired = true)]
    public uint Version { get; set; }

    [global::ProtoBuf.ProtoMember(2, Name = @"node")]
    public HDNodeType Node { get; set; }

    [global::ProtoBuf.ProtoMember(3, Name = @"mnemonic")]
    [global::System.ComponentModel.DefaultValue("")]
    public string Mnemonic
    {
        get { return __pbn__Mnemonic ?? ""; }
        set { __pbn__Mnemonic = value; }
    }
    public bool ShouldSerializeMnemonic() => __pbn__Mnemonic != null;
    public void ResetMnemonic() => __pbn__Mnemonic = null;
    private string __pbn__Mnemonic;

    [global::ProtoBuf.ProtoMember(4, Name = @"passphrase_protection")]
    public bool PassphraseProtection
    {
        get { return __pbn__PassphraseProtection.GetValueOrDefault(); }
        set { __pbn__PassphraseProtection = value; }
    }
    public bool ShouldSerializePassphraseProtection() => __pbn__PassphraseProtection != null;
    public void ResetPassphraseProtection() => __pbn__PassphraseProtection = null;
    private bool? __pbn__PassphraseProtection;

    [global::ProtoBuf.ProtoMember(5, Name = @"pin_failed_attempts")]
    public uint PinFailedAttempts
    {
        get { return __pbn__PinFailedAttempts.GetValueOrDefault(); }
        set { __pbn__PinFailedAttempts = value; }
    }
    public bool ShouldSerializePinFailedAttempts() => __pbn__PinFailedAttempts != null;
    public void ResetPinFailedAttempts() => __pbn__PinFailedAttempts = null;
    private uint? __pbn__PinFailedAttempts;

    [global::ProtoBuf.ProtoMember(6, Name = @"pin")]
    [global::System.ComponentModel.DefaultValue("")]
    public string Pin
    {
        get { return __pbn__Pin ?? ""; }
        set { __pbn__Pin = value; }
    }
    public bool ShouldSerializePin() => __pbn__Pin != null;
    public void ResetPin() => __pbn__Pin = null;
    private string __pbn__Pin;

    [global::ProtoBuf.ProtoMember(7, Name = @"language")]
    [global::System.ComponentModel.DefaultValue("")]
    public string Language
    {
        get { return __pbn__Language ?? ""; }
        set { __pbn__Language = value; }
    }
    public bool ShouldSerializeLanguage() => __pbn__Language != null;
    public void ResetLanguage() => __pbn__Language = null;
    private string __pbn__Language;

    [global::ProtoBuf.ProtoMember(8, Name = @"label")]
    [global::System.ComponentModel.DefaultValue("")]
    public string Label
    {
        get { return __pbn__Label ?? ""; }
        set { __pbn__Label = value; }
    }
    public bool ShouldSerializeLabel() => __pbn__Label != null;
    public void ResetLabel() => __pbn__Label = null;
    private string __pbn__Label;

    [global::ProtoBuf.ProtoMember(9, Name = @"imported")]
    public bool Imported
    {
        get { return __pbn__Imported.GetValueOrDefault(); }
        set { __pbn__Imported = value; }
    }
    public bool ShouldSerializeImported() => __pbn__Imported != null;
    public void ResetImported() => __pbn__Imported = null;
    private bool? __pbn__Imported;

    [global::ProtoBuf.ProtoMember(10, Name = @"policies")]
    public global::System.Collections.Generic.List<PolicyType> Policies { get; } = new global::System.Collections.Generic.List<PolicyType>();

}

#pragma warning restore CS1591, CS0612, CS3021, IDE1006
