// This file was generated by a tool; you should avoid making direct changes.
// Consider using 'partial classes' to extend these types
// Input: messages-nano.proto

#pragma warning disable

namespace KeepKey.Net.Contracts
{

    [global::ProtoBuf.ProtoContract()]
    public partial class NanoGetAddress : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"address_n")]
        public uint[] AddressNs { get; set; }

        [global::ProtoBuf.ProtoMember(2, Name = @"coin_name")]
        [global::System.ComponentModel.DefaultValue(@"Nano")]
        public string CoinName
        {
            get { return __pbn__CoinName ?? @"Nano"; }
            set { __pbn__CoinName = value; }
        }
        public bool ShouldSerializeCoinName() => __pbn__CoinName != null;
        public void ResetCoinName() => __pbn__CoinName = null;
        private string __pbn__CoinName;

        [global::ProtoBuf.ProtoMember(3, Name = @"show_display")]
        public bool ShowDisplay
        {
            get { return __pbn__ShowDisplay.GetValueOrDefault(); }
            set { __pbn__ShowDisplay = value; }
        }
        public bool ShouldSerializeShowDisplay() => __pbn__ShowDisplay != null;
        public void ResetShowDisplay() => __pbn__ShowDisplay = null;
        private bool? __pbn__ShowDisplay;

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class NanoAddress : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"address")]
        [global::System.ComponentModel.DefaultValue("")]
        public string Address
        {
            get { return __pbn__Address ?? ""; }
            set { __pbn__Address = value; }
        }
        public bool ShouldSerializeAddress() => __pbn__Address != null;
        public void ResetAddress() => __pbn__Address = null;
        private string __pbn__Address;

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class NanoSignTx : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"address_n")]
        public uint[] AddressNs { get; set; }

        [global::ProtoBuf.ProtoMember(2, Name = @"coin_name")]
        [global::System.ComponentModel.DefaultValue(@"Nano")]
        public string CoinName
        {
            get { return __pbn__CoinName ?? @"Nano"; }
            set { __pbn__CoinName = value; }
        }
        public bool ShouldSerializeCoinName() => __pbn__CoinName != null;
        public void ResetCoinName() => __pbn__CoinName = null;
        private string __pbn__CoinName;

        [global::ProtoBuf.ProtoMember(3)]
        public ParentBlock parent_block { get; set; }

        [global::ProtoBuf.ProtoMember(4, Name = @"link_hash")]
        public byte[] LinkHash
        {
            get { return __pbn__LinkHash; }
            set { __pbn__LinkHash = value; }
        }
        public bool ShouldSerializeLinkHash() => __pbn__LinkHash != null;
        public void ResetLinkHash() => __pbn__LinkHash = null;
        private byte[] __pbn__LinkHash;

        [global::ProtoBuf.ProtoMember(5, Name = @"link_recipient")]
        [global::System.ComponentModel.DefaultValue("")]
        public string LinkRecipient
        {
            get { return __pbn__LinkRecipient ?? ""; }
            set { __pbn__LinkRecipient = value; }
        }
        public bool ShouldSerializeLinkRecipient() => __pbn__LinkRecipient != null;
        public void ResetLinkRecipient() => __pbn__LinkRecipient = null;
        private string __pbn__LinkRecipient;

        [global::ProtoBuf.ProtoMember(6, Name = @"link_recipient_n")]
        public uint[] LinkRecipientNs { get; set; }

        [global::ProtoBuf.ProtoMember(7, Name = @"representative")]
        [global::System.ComponentModel.DefaultValue("")]
        public string Representative
        {
            get { return __pbn__Representative ?? ""; }
            set { __pbn__Representative = value; }
        }
        public bool ShouldSerializeRepresentative() => __pbn__Representative != null;
        public void ResetRepresentative() => __pbn__Representative = null;
        private string __pbn__Representative;

        [global::ProtoBuf.ProtoMember(8, Name = @"balance")]
        public byte[] Balance
        {
            get { return __pbn__Balance; }
            set { __pbn__Balance = value; }
        }
        public bool ShouldSerializeBalance() => __pbn__Balance != null;
        public void ResetBalance() => __pbn__Balance = null;
        private byte[] __pbn__Balance;

        [global::ProtoBuf.ProtoMember(9, Name = @"exchange_type")]
        public ExchangeType ExchangeType { get; set; }

        [global::ProtoBuf.ProtoContract()]
        public partial class ParentBlock : global::ProtoBuf.IExtensible
        {
            private global::ProtoBuf.IExtension __pbn__extensionData;
            global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
                => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

            [global::ProtoBuf.ProtoMember(1, Name = @"parent_hash")]
            public byte[] ParentHash
            {
                get { return __pbn__ParentHash; }
                set { __pbn__ParentHash = value; }
            }
            public bool ShouldSerializeParentHash() => __pbn__ParentHash != null;
            public void ResetParentHash() => __pbn__ParentHash = null;
            private byte[] __pbn__ParentHash;

            [global::ProtoBuf.ProtoMember(2, Name = @"link")]
            public byte[] Link
            {
                get { return __pbn__Link; }
                set { __pbn__Link = value; }
            }
            public bool ShouldSerializeLink() => __pbn__Link != null;
            public void ResetLink() => __pbn__Link = null;
            private byte[] __pbn__Link;

            [global::ProtoBuf.ProtoMember(4, Name = @"representative")]
            [global::System.ComponentModel.DefaultValue("")]
            public string Representative
            {
                get { return __pbn__Representative ?? ""; }
                set { __pbn__Representative = value; }
            }
            public bool ShouldSerializeRepresentative() => __pbn__Representative != null;
            public void ResetRepresentative() => __pbn__Representative = null;
            private string __pbn__Representative;

            [global::ProtoBuf.ProtoMember(5, Name = @"balance")]
            public byte[] Balance
            {
                get { return __pbn__Balance; }
                set { __pbn__Balance = value; }
            }
            public bool ShouldSerializeBalance() => __pbn__Balance != null;
            public void ResetBalance() => __pbn__Balance = null;
            private byte[] __pbn__Balance;

        }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class NanoSignedTx : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"signature")]
        public byte[] Signature
        {
            get { return __pbn__Signature; }
            set { __pbn__Signature = value; }
        }
        public bool ShouldSerializeSignature() => __pbn__Signature != null;
        public void ResetSignature() => __pbn__Signature = null;
        private byte[] __pbn__Signature;

        [global::ProtoBuf.ProtoMember(2, Name = @"block_hash")]
        public byte[] BlockHash
        {
            get { return __pbn__BlockHash; }
            set { __pbn__BlockHash = value; }
        }
        public bool ShouldSerializeBlockHash() => __pbn__BlockHash != null;
        public void ResetBlockHash() => __pbn__BlockHash = null;
        private byte[] __pbn__BlockHash;

    }
}

#pragma warning restore
